import Link from "next/link";
import { CalendarDays, Vote } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getPublicElections } from "@/lib/public-elections";

export default async function VoteHomePage() {
  const elections = await getPublicElections();
  return <div className="space-y-10"><section className="rounded-3xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-950 p-7 sm:p-10"><div className="max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-4 py-2 text-sm text-cyan-300"><Vote size={16} aria-hidden="true" />Available elections</div><h1 className="text-4xl font-bold leading-tight text-white sm:text-5xl">Choose an election and cast your ballot.</h1><p className="mt-5 text-base leading-7 text-slate-400 sm:text-lg">Open published elections and follow the voting flow selected by the organiser.</p></div></section><div><h2 className="text-3xl font-bold text-white">Available Elections</h2><p className="mt-2 text-slate-400">Select an election below to begin.</p></div>{elections.length === 0 ? <div className="rounded-3xl border border-dashed border-slate-700 bg-slate-900 py-20 text-center"><Vote size={52} className="mx-auto mb-5 text-slate-600" aria-hidden="true" /><h3 className="text-2xl font-bold text-white">No published elections</h3><p className="mt-3 text-slate-400">There are currently no elections available.</p></div> : <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{elections.map((election) => <article key={election.id} className="rounded-3xl border border-slate-800 bg-slate-900 p-7 transition hover:border-cyan-500/50"><span className="rounded-full bg-emerald-500/10 px-3 py-1 text-sm font-medium text-emerald-300">Published</span><h3 className="mt-5 text-2xl font-bold text-white">{election.title}</h3><p className="mt-3 line-clamp-3 text-slate-400">{election.description || "No description provided."}</p><div className="mt-6 space-y-2 text-sm text-slate-400"><div className="flex items-center gap-2"><CalendarDays size={16} aria-hidden="true" />Starts {new Date(election.start_date).toLocaleDateString()}</div><div className="flex items-center gap-2"><CalendarDays size={16} aria-hidden="true" />Ends {new Date(election.end_date).toLocaleDateString()}</div></div><Link href={`/elections/${election.id}`} className="mt-7 block"><Button className="w-full bg-cyan-500 text-slate-950 hover:bg-cyan-400">Open election</Button></Link></article>)}</div>}</div>;
}
